version: "3"
services:
  frontend:
    image: my-frontend-app
    ports:
      - "8080:80"
    networks:
      - myapp-network

  backend:
    image: mohomedaadil/flask-rest-api:0.0.1.RELEASE
    ports:
      - "3000:3000"
    networks:
      - myapp-network
networks:
  myapp-network:
